### ISSUE TITLE
Multiple setenv's in the clamp.json

### ISSUE THREAD

**Issue by JaredSartin** [jide/clamp#10]
How would one accomplish this? I would love to not have my .htaccess contain these.

**Comment by JaredSartin** [comment]
ping.

**Comment by jide** [comment]
You can probably use this trick in clamp.json, but I did not test... tell me if it works :) 
```json
"apache": {
    "commands": {
        "httpd": "sudo httpd -c 'setenv TEST true' -c 'setenv OTHER false'"
    }
}
```
