### ISSUE TITLE
Many PHP versions ?

### ISSUE THREAD

**Issue by maximelebastard** [jide/clamp#13]
Is there any way to manage many php versions ?

**Comment by jide** [comment]
You can use a custom clamp.json file by doing `clamp config write` and then edit the file to modify the apache config and tell it what php lib you want to use. You could use homebrew to install a custom php version and then point apache config to use it :

```
    "apache": {
        // ...
        "options": {
            // ...
            "loadmodule": {
                // ...
                // Here point it to your custom PHP lib :
                "php5_module": "/usr/libexec/apache2/libphp5.so"
            }
        }
    },
```

**Comment by maximelebastard** [comment]
Ok, thanks !

2015-08-21 15:08 GMT+02:00 Jidé <notifications@github.com>:
