### ISSUE TITLE
MySQL 5.7 and PHP 7 - combo possible?

### ISSUE THREAD

**Issue by masterbee** [jide/clamp#15]
hi @jide,

Just wondering if there was any thought on how to leverage MySQL 5.7 and PHP 7?

**Comment by masterbee** [comment]
@jide - just sending a small nudge to see if there was any appetite for my above question.

**Comment by jide** [comment]
Hi @masterbee,

It should be possible, but tbh it's been a long time since i did not do anything php related and thus did not use my own lib :)

You can try to tweak the config file and pointing it to the good paths, see this issue https://github.com/jide/clamp/issues/13
