### ISSUE TITLE
Warning while updating homebrew

### ISSUE THREAD

**Issue by aldorr** [jide/clamp#16]
Warning: Calling Formula.sha1 is deprecated!
Use Formula.sha256 instead.
/usr/local/Library/Taps/jide/homebrew-clamp/clamp.rb:7:in `class:Clamp'
Please report this to the jide/clamp tap!

Warning: Calling SoftwareSpec#sha1 is deprecated!
Use SoftwareSpec#sha256 instead.
/usr/local/Library/Taps/jide/homebrew-clamp/clamp.rb:7:in `class:Clamp'
Please report this to the jide/clamp tap!

Warning: Calling Resource#sha1 is deprecated!
Use Resource#sha256 instead.
/usr/local/Library/Taps/jide/homebrew-clamp/clamp.rb:7:in `class:Clamp'
Please report this to the jide/clamp tap!

**Comment by rqelibari** [comment]
This issue is solved. It was an error in the homebrew repository of clamp.

**Comment by aldorr** [comment]
Thanks, I haven't been using clamp in a while. But have to give it a try again. Thanks again!
