### ISSUE TITLE
500 error when loading localhost content

### ISSUE THREAD

**Issue by andreborud** [jide/clamp#19]
I had the same problem as in #18 which I fixed with the "dirty" fix. And now whenever I load the localhost content. 

In the apache.error.log I get the following:

`[Fri Oct 21 16:41:12.682200 2016] [core:notice] [pid 2439] AH00094: Command line: 'httpd -f /dev/null -c servername localhost -c listen 80 -c documentroot '/Users/andre/Dropbox/development/html-viewer/public_html' -c serverroot '/Users/andre/Dropbox/development/html-viewer/public_html' -c pidfile '/Users/andre/Dropbox/development/html-viewer/public_html/.clamp/tmp/httpd.pid' -c loglevel info -c errorlog '/Users/andre/Dropbox/development/html-viewer/public_html/.clamp/logs/apache.error.log' -c customlog '/Users/andre/Dropbox/development/html-viewer/public_html/.clamp/logs/apache.access.log' common -c addtype application/x-httpd-php .php -c directoryindex index.html index.php -c setenv LOCAL_SERVER true -c user andre -c group _www -c loadmodule authz_host_module /usr/libexec/apache2/mod_authz_host.so -c loadmodule dir_module /usr/libexec/apache2/mod_dir.so -c loadmodule env_module /usr/libexec/apache2/mod_env.so -c loadmodule mime_module /usr/libexec/apache2/mod_mime.so -c loadmodule log_config_module /usr/libexec/apache2/mod_log_config.so -c loadmodule rewrite_module /usr/libexec/apache2/mod_rewrite.so -c loadmodule php5_module /usr/libexec/apache2/libphp5.so -c loadmodule unixd_module /usr/libexec/apache2/mod_unixd.so -c php_admin_value memory_limit 256M -c php_admin_value pdo_mysql.default_socket '/Users/andre/Dropbox/development/html-viewer/public_html/.clamp/tmp/mysql.sock' -c php_admin_value mysql.default_socket '/Users/andre/Dropbox/development/html-viewer/public_html/.clamp/tmp/mysql.sock' -c php_admin_value mysqli.default_socket '/Users/andre/Dropbox/development/html-viewer/public_html/.clamp/tmp/mysql.sock''
[Fri Oct 21 16:41:23.764204 2016] [core:crit] [pid 2440] [client ::1:50275] AH00025: configuration error:  couldn't check user: /index.html`

and in clamp.json I have put my username in here:

```
"apache": {
        "commands": {
            "httpd": "sudo httpd"
        },
        "options": {
            ...
            "user": "andre",
...
```

Said "`whois`" before and gave the same error. 

What to do?

By the way. This is by far the best Apache client I have used!

**Comment by rqelibari** [comment]
Hi @andreborud,

Sorry for the way to late answer. I was busy with a project of mine. This year I will have a lot more time for this great project by @jide. I will provide an update soon (I think it should be ready Friday next Week, 09. Jan.). That update should fix this issue and some others too.

A quickfix is to grab a copy of [clamp.defaults.15.json](https://github.com/jide/clamp/blob/master/clamp.defaults.15.json) and start with that file as a config file for your project. This will fix a lot. Remember, that you will have to rename that file to "config.json".

**Comment by andreborud** [comment]
Thanks @rqelibari. That did the trick!
