### ISSUE TITLE
XDebug issue

### ISSUE THREAD

**Issue by hanvari** [jide/clamp#23]
Hi,
I’m trying to use XDebug for debugging my PHP scripts, but apparently this module is not available.
Currently I added a configuration to ‘php’ entry of clamp.json, setting “xdebug.remote_autostart” to 1, but it doesn’t do anything (I think the module is not loaded at all).
How can I enable and use it?

Thanks.

**Comment by jide** [comment]
You could probably use a custom php module with xdebug and point at it here https://github.com/jide/clamp/blob/master/clamp.defaults.15.json#L35. But I'm not sure.
