### ISSUE TITLE
AH00072: make_sock: could not bind to address 0.0.0.0:80

### ISSUE THREAD

**Issue by seankmchenry** [jide/clamp#24]
Getting this error on OSX Sierra, even on a clean start-up or reboot (no Vagrant or LAMP/LEMP stacks running). When I run `clamp apache start` the following is returned in the terminal:

```
(48)Address already in use: AH00072: make_sock: could not bind to address [::]:80
(48)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:80
no listening sockets available, shutting down
AH00015: Unable to open logs
```

Any troubleshooting suggestions would be greatly appreciated!

**Comment by rqelibari** [comment]
> Address already in use

This log message suggests that you have already something running at port 80. Is that possible?

**Comment by rqelibari** [comment]
I am closing this issue, if this arises again, open a new issue.
