### ISSUE TITLE
.htaccess RedirectMatch results in "Invalid command 'RedirectMatch'"

### ISSUE THREAD

**Issue by alanfluff** [jide/clamp#25]
Hi,

I have `clamp` working AOK but I am seeing in `apache.error.log`:

`[Sun Jun 18 18:45:20.997647 2017] [core:alert] [pid 51008] [client ::1:57746] /Users/me/example.com/.htaccess: Invalid command 'RedirectMatch', perhaps misspelled or defined by a module not included in the server configuration, referer: http://localhost/`

if my `.htaccess' file includes:

`RedirectMatch 301 ^/info/$      http://example/`

This happens even if I simply try to access http://localhost (not /info).

If I comment out the `RedirectMatch` line (and all following `Redirect 301 ...` lines) then the site renders AOK.

I have the good `.htaccess` setting:

~~~
<IfModule mod_authz_core.c>
    Require all denied
  </IfModule>
  <IfModule !mod_authz_core.c>
    Order allow,deny
  </IfModule>
~~~

as suggested at `https://jide.github.io/clamp/`.

Is this a known issue, or can I provide more info to perhaps help solve this.

`clamp` is brilliant ^_^

**Comment by rqelibari** [comment]
`RedirectMatch` is part of [mod_alias][1]. This module is not loaded by default.
Insert the following line into your `clamp.conf` file:

    {...
        "apache": {...
            "options" {...
                "loadmodule": {
                    ...
                    "alias_module": "/usr/libexec/apache2/mod_alias.so",
                    ...
                }
            }
        }
    }

[1]: https://httpd.apache.org/docs/2.4/mod/mod_alias.html

**Comment by alanfluff** [comment]
Thanks @rqelibari - I'll go try that now and post back to confirm, cheers! ^_^

**Comment by alanfluff** [comment]
@rqelibari The only thing was a typo, I edited it into `clamp.json` not `clamp.conf` but that aside, WORKED! ^_^ Thank you, clamp is brilliant!
