### ISSUE TITLE
Configuring php7_module will prevent clamp from starting

### ISSUE THREAD

**Issue by blynx** [jide/clamp#28]
I installed this https://php-osx.liip.ch PHP package on macOS Sierra and put the appropriate path into the apache options, also removed `php5_module`.

    "php7_module": "/usr/local/php5/libphp7.so"

But clamp won't init anything anymore.

**Comment by rqelibari** [comment]
Which script of that site did you actually run on your system?
Have you already checked if the library at `/usr/local/php5/libphp7.so` really exists?

**Comment by blynx** [comment]
It is the latest (7.2 for 10.10 and later) resulting in: php5-7.2.0RC2-20170914-192030
Yep, that file exists.

Maybe to clarify my initial post, I put the options into the clamp config file which I got with `clamp config write`

**Comment by alanfluff** [comment]
Over on #29 I still can't get clamp to start or any output in the contents under /logs/ when using a .clamp with `"php7_module": "/usr/libexec/apache2/libphp7.so"` - clamp (or OS X) returns an error that suggests it's still looking for `libphp5.so` even though now on OS X 10.13 that file is gone, replaced with `libphp7.so` and the .clamp no longer references it (sorry for cross posting, but this looked related).

**Comment by rqelibari** [comment]
The next release will come on Friday and that should fix those problems.
@blynx: Can you tell me which script of the many on php-osx.liip.ch you used?

**Comment by blynx** [comment]
Nice,
this installer: "PHP 7.2 (Next stable) - 10.10 and later"  
 `curl -s https://php-osx.liip.ch/install.sh | bash -s 7.2`

**Comment by rqelibari** [comment]
This issue has now been resolved with the [1.4.2](https://github.com/jide/clamp/releases/tag/1.4.2) release.
