### ISSUE TITLE
Enhancement: Browser

### ISSUE THREAD

**Issue by perasmus** [jide/clamp#4]
Hello,

another minor idea: would it be useful to add something like this to the end of the main script?
`open http://<adress>`
this should / could open the defined url in the preferred browser after starting the server. It could be enabled/disabled via the clamp.json à la `"autoopen": true`

**Comment by rqelibari** [comment]
I am glad to announce that this feature has been implemented in [v.1.3.4][1].
I am closing this issue therefor.

[1]: https://github.com/jide/clamp/releases/tag/1.3.4
