### ISSUE TITLE
improvement: change default to non-privileged port

### ISSUE THREAD

**Issue by aerickson** [jide/clamp#41]
Currently defaults to port 80. Clamp is for development and local testing... port 80 isn't the best and it requires sudo on most versions of OS X (<10.14).

Thoughts on what port it should be? 8080? Perhaps too common?

**Comment by rqelibari** [comment]
Looking at other webdev projects:

* react uses port 3000
* CodeKit: 8888
* Other react based forks: 5000

It seems there is no real pattern here. In my opinion we are free to choose any non standard port above 1023.

**Comment by aerickson** [comment]
#42 is merged. Closing.
