### ISSUE TITLE
configure travis for clamp

### ISSUE THREAD

**Issue by aerickson** [jide/clamp#44]
We have a travis config file, but Travis isn't looking at the code yet because we haven't set up the integration.

I think all that is required is for someone with commit access to this repo to visit https://travis-ci.org/jide/clamp and configure the integration (it was easy when I did it for my fork).

**Comment by rqelibari** [comment]
Only @jide himself can activate the repo on travis.

@jide What do you think?

**Comment by jide** [comment]
I'm not sure why I can't give you full admin access to the repo on github @rqelibari. But I did activate the repo for travis, do you confirm it's okay ?

**Comment by rqelibari** [comment]
@jide Thank you! Should be fine now. I triggered a first build and it worked like a charm ([Log](https://travis-ci.org/jide/clamp/builds/493671735)).
