### ISSUE TITLE
remove sudo

### ISSUE THREAD

**Issue by jide** [jide/clamp#6]
@see http://www.snip2code.com/Snippet/176829/How-to-install-Clamp-without-sudo

**Comment by aerickson** [comment]
Here's a quick hack that removes sudo. https://github.com/aerickson/clamp/tree/no_sudo

Seems to work from some very brief testing (not sure why as it's serving off of port 80 and I'm not running with sudo... some strange 10.14 stuff - https://news.ycombinator.com/item?id=18302380).

**Comment by rqelibari** [comment]
That is a nice development, indeed! Thanks for pointing that out, @aerickson!
Would you mind creating a pull request for that?

**Comment by aerickson** [comment]
I can for sure. Would you like me to change the port to something other than 80? It's only going to work on 10.14 unless we change it to something like 8080.

**Comment by rqelibari** [comment]
I would suggest that you modify the `executeWrite` method in `./includes/Clamp/ConfigCommand.php` to modify the default port, if it is running on Darwin kernel > 17.

You can easily find out the major version of the Darwin kernel by using:
```php
substr(php_uname('r'), 0, 2);
```
Thank you for wanting to implement this feature. I think the users will appreciate that feature.

Addition: Please do not forget to properly document the changes in code and update the README :-)

**Comment by aerickson** [comment]
How about displaying an error if the port will likely require root/sudo (if on <10.14 and port <1024)? 

I think that the program shouldn't change what the user has specified in the config file.

**Comment by rqelibari** [comment]
I totally agree, that the program should not change what the user has specified in their config file.
What I suggest is to modify the default config file that you get with `clamp config write` when you start a new project. And I suggested to modify it 'on the fly', if the script is run on Darwin kernel > 17.

About the "on the fly" changes I am not so sure anymore. Come to think that we want to remove sudo too, a third default config file named `clamp.defaults.18.json` would make much more sense.

## Conclusion
Starting from the latest master commit [`6ab1377`](https://github.com/jide/clamp/commit/6ab13777fa4f3702d63a7fd77041c929a0045388) I suggest the following approach to remove sudo:

1. Copy `clamp.defaults.json` to `clamp.defaults.18.json`.
2. Modify `clamp.defaults.18.json` and remove `sudo` calls.
3. Modify the [Apache](https://github.com/jide/clamp/blob/master/includes/Clamp/ApacheCommand.php) and [MySQL](https://github.com/jide/clamp/blob/master/includes/Clamp/MysqlCommand.php) commands to kill the processes with `sudo` only if they have been started with `sudo`.
4. Do not modify the [Host]() command, but instead make it skipable. When run it will ask for `sudo` password to modify the `hosts` file, but afterwards `clamp` can run without `sudo`.

What do you think about that approach?

**Comment by aerickson** [comment]
I think we can close this. :)
