### ISSUE TITLE
nginx support

### ISSUE THREAD

**Issue by thiagodebastos** [jide/clamp#7]
I thought I would commend you for this, the **easiest** lamp setup I have ever used!

I'm a newb to non-gui-ness and was wondering how would I go about adding nginx support?

**Comment by fulldecent** [comment]
This appears to be out of project scope "Command Line Apache MySQL PHP".

Recommending to close issue.

**Comment by rqelibari** [comment]
@thiagodebastos `clamp` exists because it wants to make development on macOS easy. nginx isn't preinstalled on macOS though and falls out of the scope of clamp. If you'd like to support it as an extended feature, we'd be happy to include it though.

**Comment by thiagodebastos** [comment]
Sorry to revive this, I'm closing out old issues. Thank you (a few years later) for your answer!

**Comment by thiagodebastos** [comment]
Sorry to revive this, I'm closing out old issues. Thank you (a few years later) for your answer!
